name: raylib-@0.1.6-build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build raylib_lucia
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GCC on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y gcc make libx11-dev libxcursor-dev libxrandr-dev libxi-dev libxinerama-dev libgl1-mesa-dev libglu1-mesa-dev

      - name: Install GCC on macOS
        if: runner.os == 'macOS'
        run: brew install gcc

      - name: Install GCC on Windows
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-gcc
          
      - name: List binding folder
        if: runner.os == 'Linux'
        working-directory: raylib_lucia/@0.1.6
        run: ls -R lib/binding

      - name: Build raylib_lucia on Linux
        if: runner.os == 'Linux'
        working-directory: raylib_lucia/@0.1.6
        run: |
            gcc -o lib/raylib_lucia.so \
            lib/binding/raylib_lucia_bindings.c \
            -I./lib/binding ./lib/raylib_linux.a \
            -fPIC -lm -lX11 -lGL -lGLU -ldl -lpthread

      - name: Build raylib_lucia on macOS
        if: runner.os == 'macOS'
        working-directory: raylib_lucia/@0.1.6
        run: |
            gcc -dynamiclib -o lib/raylib_lucia.dylib \
            lib/binding/raylib_lucia_bindings.c \
            -I./lib/binding ./lib/raylib_macos.a \
            -framework Cocoa -framework IOKit -framework CoreVideo -framework CoreFoundation -framework OpenGL


      - name: Build raylib_lucia on Windows
        if: runner.os == 'Windows'
        shell: bash
        working-directory: raylib_lucia/@0.1.6
        run: gcc -o lib/raylib_lucia.dll lib/binding/raylib_lucia_bindings.c -I./lib/binding ./lib/raylib_windows.a -static

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: raylib_lucia-${{ runner.os }}
          path: raylib_lucia/@0.1.6/lib/raylib_lucia.*
